### ISSUE TITLE
Wpf deskband creates empty entry in toolbar menu

### ISSUE THREAD

**Issue by dsafa** [dsafa/CSDeskBand#23]
![2018-01-18_21-04-15](https://user-images.githubusercontent.com/7334282/35135658-72432970-fc93-11e7-952e-a1fc879bd2c2.jpg)

When the wpf deskband is activated, it appears as a blank entry which allows it to be duplicated by selecting it again from the toolbars menu. Normally, the entry is checkmarked when it is activated (see the winforms sample in the above screenshot)

**Comment by brian9206** [comment]
This issue is caused by blank title. It can be addressed as follow: [line 150-153](https://github.com/brian9206/CSDeskBand/blob/b26b8c767046b2aeab0b90c4913477ccfd6ed03d/CSDeskBand/CSDeskBandImpl.cs#L150)
However, it does not have the same behavior as winform because it adds an entry in the menu instead of having the original entry checked
